jcr:
  build: .
  ports:
   - 8888:8080
  volumes:
   - "~/nice.fr/jackrabbit/jackrabbit:/opt/jackrabbit"

elasticsearch:
  image: dockerfile/elasticsearch
  ports:
  - 9200:9200
  - 9300:9300
  volumes:
   - "~/nice.fr/elasticsearch:/data"

mysql:
  image: mysql
  volumes:
   - "~/nice.fr/mysql:/var/lib/mysql"
  environment:
   - MYSQL_ROOT_PASSWORD=dbpass
  ports:
  - 3306:3306